authors = Author.create([{ name:  'J. R. R. Tolkien' }, { name: 'Eckhart Tolle' }, { name: 'Robert C. Martin' }, { name: 'J. K. Rowling' }])
collections = Books::Collection.create([{ title: 'The Lord of Rings' }, { title: 'Harry Potter' }])

Book.create(author: authors.first, title: 'The Hobbit', isbn: '9780582186552', description: 'The Hobbit is a tale of high adventure, undertaken by a company of dwarves in search of dragon-guarded gold. A reluctant partner in this perilous quest is Bilbo Baggins, a comfort-loving unambitious hobbit, who surprises even himself by his resourcefulness and skill as a burglar.', price: 25.00)
Book.create(author: authors.first, collection: collections.first, title: 'The Fellowship of the Ring', isbn: '9788071457060', description: 'The first part of the Lord of the Rings trilogy, Tolkien’s classic epic of Good versus Evil, set in the fictional world of Middle Earth, this book introduces the main characters and sets Frodo the Hobbit and his companions on their quest to return the ring of the evil Sauron to the fires of Mordor.', price: 25.00)
Book.create(author: authors.first, collection: collections.first, title: 'The Two Towers', isbn: '9788372980618', description: 'Frodo and the Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in the battle with an evil spirit in the Mines of Moria.', price: 25.00)
Book.create(author: authors.first, collection: collections.first, title: "The Return of the King', isbn: '9780261102941', description: 'THE RETURN OF THE KING, which brings to a close the great epic of war and adventure begun in The Fellowship of the Ring and continued in The Two Towers, is the third and final part of J. R. R. Tolkien's masterpiece, 'The Lord of the Rings.'", price: 25.00)

Book.create(author: authors.second, title: 'The Power of Now', isbn: '9781577312192', description: 'To make the journey into The Power of Now we will need to leave our analytical mind and its false created self, the ego, behind. From the beginning of the first chapter we move rapidly into a significantly higher altitude where one breathes a lighter air, the air of the spiritual.', price: 19.00)
Book.create(author: authors.second, title: "A New Earth: Awakening to Your Life's Purpose", isbn: '9788721034351', description: 'The highly anticipated follow-up to the 2,000,000 copy bestselling inspirational book, The Power of NowWith his bestselling spiritual guide The Power of Now, Eckhart Tolle inspired millions of readers to discover the freedom and joy of a life lived "in the now."', price: 19.00)

Book.create(author: authors.third, title: 'Clean Code', isbn: '9788025122853', description: "Even bad code can function. But if code isn't clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code.", price: 35.00)
Book.create(author: authors.third, title: "Clean Archtecture: A Craftsman's Guide to Software Structure and Design", isbn: '9788721034351', description: 'By applying universal rules of software architecture, you can dramatically improve developer productivity throughout the life of any software system. Now, building upon the success of his best-selling books Clean Code and The Clean Coder.', price: 35.00)

Book.create(author: authors.fourth, collection: collections.second, title: "Harry Potter and The Philosopher's Stone", isbn: '9789513114725', description: "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle.", price: 30.00)
Book.create(author: authors.fourth, collection: collections.second, title: "Harry Potter and the Chamber of Secrets", isbn: '9780605928183', description: "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year.", price: 30.00 )
Book.create(author: authors.fourth, collection: collections.second, title: "Harry Potter and the Prisoner of Azkaban", isbn: '9789994030149', description: "When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far from ordinary year at Hogwarts for Harry Potter. Sirius Black, escaped mass-murderer and follower of Lord Voldemort, is on the run - and they say he is coming after Harry. In his first ever Divination class.", price: 30.00 )
Book.create(author: authors.fourth, collection: collections.second, title: "Harry Potter and the Goblet of Fire", isbn: '9788498386639', description: "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the dark forces.", price: 30.00 )
Book.create(author: authors.fourth, collection: collections.second, title: "Harry Potter and the Order of the Phoenix", isbn: '9788498383621', description: '', price: 30.00 )
Book.create(author: authors.fourth, collection: collections.second, title: "Harry Potter and the Half-Blood Prince", isbn: '9788884516374', description: 'When Dumbledore arrives at Privet Drive one summer night to collect Harry Potter, his wand hand is blackened and shrivelled, but he does not reveal why. Secrets and suspicion are spreading through the wizarding world, and Hogwarts itself is not safe. Harry is convinced that Malfoy bears the Dark Mark: there is a Death Eater amongst them.', price: 30.00 )
Book.create(author: authors.fourth, collection: collections.second, title: "Harry Potter and the Deathly Hallows", isbn: '9780605039070', description: "As he climbs into the sidecar of Hagrid's motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are not far behind.", price: 30.00 )
